config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/home", to: "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/signup", to: "users#create"
  resources :users do
    member do
      get :following, :followers
    end
  end
  namespace :admin do
    resources :users, only: [:index]
    resources :words
  end
  resources :categories
  resources :words
  resources :relationships
  resources :lessons
end

app/models/user.rb
class User < ActiveRecord::Base

  include Sort

  has_many :lessons
  has_many :relationships
  has_many :activities
  has_many :active_relationships, class_name: "Relationship",
    foreign_key: "follower_id",
    dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
    foreign_key: "followed_id",
    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  before_save {self.email = email.downcase}

  validates :fullname, presence: true, length: {maximum: 255}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  has_secure_password
  attr_accessor :remember_token

  def User.digest string
    cost = ActiveModel::SecurePassword.min_cost ?
      BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute :remember_digest, User.digest(remember_token)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute :remember_digest, nil
  end

  def current_user? current_user
    self == current_user
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  def create_activity action_type, target_id
    self.activities.build(user_id: self.id, target_id: target_id,
      action_type: action_type).save
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user, :required_admin,
    only: [:index, :edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page],
      per_page: Settings.categories_per_page).order created_at: "desc"
  end

  def destroy
    loaduser.destroy
    flash[:success] = t "page.usercontroller.deletedestroy"
    redirect_to users_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_user, except: [:new, :create, :destroy]

  def index
    @users = User.paginate(page: params[:page],
      per_page: Settings.categories_per_page).sort_desc
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "user.hello"
      redirect_to root_path
    else
      flash[:danger] = t "user.danger"
      render :new
    end
  end

  def show
    @activity = Activity.where(user_id: @user.id).order(created_at: :desc).
      paginate page: params[:page]
  end

  def destroy
    User.find_by(params[:id]).destroy
    flash[:success] = t "page.usercontroller.destroysuccess"
    redirect_to users_url
  end

  def update
    @user.update_attributes user_params
    if @user.save
      flash[:success] = t "page.usercontroller.updatesuccess"
      redirect_to :back
    else
      flash[:danger] = t "page.usercontroller.updatefail"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit :fullname, :email, :password, :password_confirmation
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def check_activity action_type, target_id, user
    case action_type
    when Activity.activity_types[:follow]
      user.fullname + t("page.activity_follow") + User.find_by(id: target_id).fullname
    when Activity.activity_types[:unfollow]
      user.fullname + t("page.activity_unfollow") + User.find_by(id: target_id).fullname
    when Activity.activity_types[:create_lesson]
      user.fullname + t("page.activity_create_lesson")
    when Activity.activity_types[:finished]
      user.fullname + t("page.activity_finish_lesson")
    else
      t "none"
    end
  end

end

app/views/users/_editform.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: @user %>
  <%= f.label :full_name %>
  <%= f.text_field :fullname, class: "form-control" %>
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
  <input type="checkbox" name="change" id="change" onClick="showPassword()"><%= t "edit.show" %>
  <br><br>
  <%= f.label :password, class: "hide-tag" %>
  <%= f.password_field :password, class: "form-control hide-tag" %>
  <%= f.label :password_confirmation, "Confirmation", class: "hide-tag"%>
  <%= f.password_field :password_confirmation, class: "form-control hide-tag" %>
  <%= f.submit t("edit.btn") , class: "btn btn-success img-center" %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build,
  remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user.current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render "unfollow" %>
  <% else %>
    <%= render "follow" %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%=  render "shared/error_messages", object: @user%>
  <%= f.label :full_name %>
  <%= f.text_field :fullname, class: "form-control" %>
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
  <%= f.label :password_confirmation, " Password Confirmation" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  <%= f.submit t("page.header.signupitem") , class: "btn btn-success img-center" %>
<% end %>

app/views/users/_login_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control",
        id: "field1" %>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control",
        id: "field2" %>
      <%= f.label :remember_me, class: "checkbox inline" do %>
        <br>
        <%= f.check_box :remember_me %>
        <span>
          <%= t "page.session.new.remember" %>
        </span>
      <% end %>
      <br>
      <%= f.submit t("page.session.new.signin"), class: "btn btn-primary"%>
    <% end %>
    <h5>
      <%= t "page.session.new.newuser" %>
      <%= link_to t("page.session.new.signupnow"), new_user_path %>
    </h5>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: @user.id),
  html: { method: :delete },
  remote: true do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<ul>
  <li>
    <%= link_to user.fullname, user_path(user) %>
  </li>
</ul>

app/views/users/edit.html.erb
<div class="container">
  <h2><%= t "edit.profile" %></h2>
  <hr>
  <div class="row well well-lg edit">
    <div class="col-md-3">
      <div class="text-center">
        <%= gravatar_for @user %>
        <br>
        <form action="http://gravatar.com" target="_blank">
          <input type="submit" value="Change avatar" class="btn btn-primary"/>
        </form>
      </div>
    </div>
    <div class="col-md-9 personal-info">
      <div class="alert alert-info alert-dismissable">
        <a class="panel-close close" data-dismiss="alert">×</a>
        <i class="fa fa-coffee"></i>
        <%= t "edit.edit" %>
      </div>
      <h3><%= t "edit.personal" %></h3>
      <%= render "users/editform" %>
    </div>
  </div>
</div>
<hr>

app/views/users/new.html.erb
<div class="container-fluid background">
  <div class="row centered-form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title text-center"><%= t "signup.signup" %></h3>
        </div>
        <div class="panel-body">
          <%= render "users/form"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="col-md-4">
    <div class="row well well-lg profile">
      <h3 class="text-center">Profile</h3>
      <br>
      <div>
        <%= gravatar_for @user %>
      </div>
      <br>
      <div>
        <h2 class="text-center"><%= @user.fullname %></h2>
        <p class="text-center"><%= @user.email %></p>
      </div>
      <div>
        <button type="button" class="btn img-center"><%= link_to "EDIT", edit_user_path(params[:id]) %></button>
      </div>
    </div>
    <% @user ||= current_user %>
    <div class="stats">
      <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
          <%= @user.following.count %>
        </strong>
        following
      </a>
      <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
          <%= @user.followers.count %>
        </strong>
        followers
      </a>
    </div>
    <%= render "follow_form" if logged_in? %>
  </div>
  <div class="col-md-8">
    <h3 class="center"><%= t("page.activity_title", name: @user.fullname) %></h3>
    <table class="table table-striped table-bordered ls-users">
      <thead class="title_table">
        <tr>
          <th><%= t "page.activity" %></th>
          <th><%= t "page.timestamp" %></th>
        </tr>
      </thead>
      <tbody>
        <% @activity.each do |activity| %>
          <%= render "shared/activity", activity: activity,
            locals: {user: @user} %>
        <% end %>
      </tbody>
    </table>
    <div class="pagingnate">
      <%= will_paginate @activity %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>