config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/home", to: "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/signup", to: "users#create"
  resources :users do
    member do
      get :following, :followers
    end
  end
  namespace :admin do
    resources :users, only: [:index]
    resources :words
  end
  resources :categories
  resources :words
  resources :relationships
  resources :lessons
end

app/models/word.rb
class Word < ActiveRecord::Base

  include Sort

  belongs_to :category
  has_many :results
  has_many :word_answers , dependent: :destroy

  validates :name, presence: true, length: {maximum: 255}
  validate :validate_answer
  accepts_nested_attributes_for :word_answers, allow_destroy: true,
    reject_if: proc{|attributes| attributes["content"].blank?}
  after_initialize :build_word_answers
  QUERY_LEARNED = "name like :search and id in (select answer_id
    FROM results r INNER JOIN lessons l
    ON r.lesson_id = l.id AND l.user_id = :user_id)"
  QUERY_ALL = "name like :search"
  QUERY_NOT_LEARNED = "name like :search and id not in (select answer_id
    FROM results r INNER JOIN lessons l
    ON r.lesson_id = l.id AND l.user_id = :user_id)"

  scope :in_category, -> category_id do
    where category_id: category_id if category_id.present?
  end

  scope :show_all, -> user_id, search do
    where QUERY_ALL, search: "%#{search}%"
  end

  scope :learned, -> (user_id, search) do
    where QUERY_LEARNED, user_id: user_id, search: "%#{search}%"
  end

  scope :not_learned, -> (user_id, search) do
    where QUERY_NOT_LEARNED, user_id: user_id, search: "%#{search}%"
  end

  scope :search, ->(keyword, category_id) do
    where("content LIKE ? OR category_id = ?", "%#{keyword}%", "#{category_id}")
  end

  scope :search_category, ->(category_id = 0) do
    where("category_id is null OR category_id = ?", "#{category_id}")
  end

  scope :filter_category, ->(category_id = 0)do
    where("category_id = ?", "#{category_id}")
  end

  private
  def build_word_answers
    if self.new_record? && self.word_answers.size == 0
      Settings.answertimes.times {self.word_answers.build}
    end
  end

  def validate_answer
    size_correct = self.word_answers.select{|answer| answer.is_correct}.size
    if size_correct == 0
      errors.add I18n.t("validate.answer"), I18n.t("validate.number")
    end
    correct_answer_size = self.word_answers.size
    if Settings.answer_default > correct_answer_size ||
      correct_answer_size > Settings.max_answer
      errors.add t("validate.size"), t("validate.condition")
    end
  end

end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user, :required_admin
  before_action :load_categories, only: [:new, :create, :edit]
  before_action :load_word, only: [:destroy, :edit, :update]

  def index
    @words = Word.paginate(page: params[:page],
      per_page: Settings.categories_per_page).sort_desc
  end

  def new
    @categories = Category.all
    @word = Word.new
  end

  def create
    @word = Word.create word_params
    if @word.save
      flash[:success] = t "word.sucessful"
      redirect_to words_path
    else
      load_categories
      render :new
    end
  end

  def edit

  end

  def destroy
    if @word.destroy
      flash[:success] = t "category.deletesuccess"
    else
      flash[:danger] = t "category.deleteerror"
    end
    redirect_to :back
  end

  def update
    @word.update_attributes word_params
    if @word.save
      flash[:success] = t "page.categoriescontroller.createsuccess"
      redirect_to :back
    else
      flash[:success] = t "page.categoriescontroller.createfail"
      redirect_to :back
    end
  end

  private
  def word_params
    params.require(:word).permit :name, :category_id,
      word_answers_attributes: [:id, :content, :is_correct, :_destroy]
  end

  def load_categories
    @categories = Category.all
  end

  def load_word
    @word = Word.find_by id: params[:id]
    unless @word
      flash[:danger] = t "word.nil"
      render file: "public/404.html", status: :not_found, layout: true
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :check_logged
  before_action :load_word, only: [:destroy, :update, :edit]
  before_action :load_category

  def index
    params[:search] ||= ""
    params[:word_filter] ||= Settings.word_filter[:all]
    @words = Word.in_category(params[:category_id])
      .send(params[:word_filter], current_user.id, params[:search])
      .paginate page: params[:page], per_page: Settings.categories_per_page
  end

  private
  def load_category
    @categories = Category.all
  end
end

app/views/words/_answer_field.html.erb
<div class="attachment fields">
  <%= f.label :caption %>
  <%= f.file_field :document %>
  <%= link_to_remove_fields "remove", f %>
</div>

app/views/words/_form.html.erb
<%= form_for @word do |f| %>
    <%= render "shared/error_messages", object: @word%>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.label :category_title %>
    <br>
    <%= f.select :category_id, options_for_select(@categories.collect{
      |category| [category.title, category.id]}, params[:category_id]) %>
    <br>
    <div class="row">
      <div class="col-md-11">
        <label for="usr">Number of Answer</label>
      </div>
      <div class="col-md-3">
        <input type="number" class="form-control" id="number" min="0" step="1">
      </div>
    </div>
    <div class="attachments">
      <%= f.fields_for :attachments do |attachment_form| %>
          <%= render 'answer_field', :f => attachment_form %>
      <% end %>
    </div>
    <%= link_to_add_fields "Attach a file or an image", f, :attachments %><br />
    <div class="modal-footer">
    <%= link_to "Create Answer", "#", class: "btn btn-success" %>
    <%= f.submit t("signup.create") , class: "btn btn-success disabled"%>
    </div>
<% end %>

app/views/words/index.html.erb
<div class="table-responsive">
  <div class="row">
    <h2 class="col-md-2"><%= t "category.word" %></h2>
    <% if @current_user.is_admin? %>
      <%= link_to t("category.createword"), new_admin_word_path,
        class: "btn-info btn col-md-2 col-md-offset-7 createcate check-answer" %>
    <% end %>
  </div>
  <div class="space"> </div>
  <div class="filter filter_padding">
    <%= form_tag words_path, method: :get, id: "search-form" do %>
      <div class="col-md-6">
        <%= t "page.category.title" %>:
        <%= select_tag( :category_id, options_for_select(@categories.collect{ |category|
          [category.title, category.id]}, params[:category_id]),
          include_blank: Settings.all, class: "form-group") %>
        <% Settings.word_filter.each do |key, status| %>
          <%= radio_button_tag :word_filter, status,
            params[:word_filter] == status %>
          <%= label_tag "page_word_filter", t("page.word.#{status}"),
            class: "font-normal" %>
        <% end %>
      </div>
      <div class="form-group col-md-6" >
        <div class="col-xs-3"></div>
        <div class="col-xs-5">
          <%= text_field_tag :search, params[:search], class: "form-control",
            placeholder: t("word.search_placeholer") %>
        </div>
        <div class="col-xs-3">
          <%= submit_tag t("word.filter"), class: "btn btn-primary clear" %>
        </div>
      </div>
    <% end %>
  </div>
  <table class="table table-striped edit">
    <thead>
    <tr>
      <th><%= t "category.index" %></th>
      <th><%= t "category.name" %></th>
      <th><%= t "category.categoryName" %></th>
      <th><%= t "category.action" %></th>
    </tr>
    </thead>
    <tbody>
    <% @words.each_with_index do |word, index| %>
      <tr>
        <td>
          <% if params[:page] ||= 1 %>
            <%= index_for params[:page], index, Settings.categories_per_page %>
          <% end %>
        </td>
        <td><%= word.name %></td>
        <td><%= word.category.title %></td>
        <td>
          <% if @current_user.is_admin? %>
            <button type="button" class="btn btn-success btn-md button-detail glyphicon
              glyphicon-info-sign" data-toggle="modal" data-target="#myModal_<%= word.id %>">
            </button>
            <%= link_to "", edit_admin_word_path(word.id), class: "btn btn-info btn-md button-detail
              glyphicon glyphicon-pencil" %>
            <button type="button" class="btn btn-danger btn-md button-detail glyphicon
              glyphicon-remove" data-toggle="modal" data-target="#myModal_delete_<%= word.id %>">
            </button>
          <% else %>
            <button type="button" class="btn btn-info btn-md button-detail glyphicon
              glyphicon-info-sign" data-toggle="modal" data-target="#myModal_<%= word.id %>">
            </button>
          <% end %>
        </td>
      </tr>
      <div class="modal fade" id="myModal_<%= word.id %>" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"><%= t "category.detail" %></h4>
            </div>
            <div class="modal-body">
              <blockquote>
                <h3>
                  <%= t "word.question" %>
                </h3>
                <div class="clearfix"></div>
                <footer>
                  <%= word.name %>
                </footer>
              </blockquote>
              <blockquote>
                <h3>
                  <%= t "word.answer" %>
                </h3>
                <% word.word_answers.each do |word_answer|
                  if word_answer.is_correct %>
                    <footer>
                      <span class="label label-success btn-xs" %>
                        <%= word_answer.content %>
                      </span>
                    </footer>
                  <% else %>
                    <footer>
                      <span class="label label-danger btn-xs" %>
                        <%= word_answer.content %>
                      </span>
                    </footer>
                  <% end %>
                <% end %>
              </blockquote>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">
                <%= t "category.close" %>
              </button>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id="myModal_delete_<%= word.id %>" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"><%= t "category.delete" %></h4>
            </div>
            <div class="modal-body">
              <p><%= t "category.areyou" %><strong><%= t "category.deletedowncase" %>
                </strong><%= t "category.record" %>
              </p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">
                <%= t "category.close" %></button>
              <%= link_to t("category.delete"), admin_word_path(word.id),
                method: :delete , class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate %>
</div>

app/views/words/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @word do |f| %>
        <%= render "/shared/error_messages", object: f.object %>
        <%= f.label :Category %>
        <%= f.select :category_id, options_for_select(
            @categories.collect{ |category| [category.title, category.id]},
            class: "form-group") %>
        <%= render "shared/error_messages", object: f.object %>
        <br/>
        <%= f.label :Questions %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label :content, "Answer" %><br />
        <div class="answers">
          <%= f.fields_for :answers do |t| %>
              <%= render "answer_field", f: t %>
          <% end %>
          <br/>
        </div>
        <span class="btn btn-primary btn-xs pull-right">
        <%= link_to_add_fields "ADD", f, :answers %>
      </span>
        <br/>
        <br/>

        <%= f.submit "CREATE", id: "create_word",
                     class: "btn btn-primary" %>
    <% end %>
  </div>
</div>