config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/home", to: "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/signup", to: "users#create"
  resources :users do
    member do
      get :following, :followers
    end
  end
  namespace :admin do
    resources :users, only: [:index]
    resources :words
  end
  resources :categories
  resources :words
  resources :relationships
  resources :lessons
end

app/models/category.rb
class Category < ActiveRecord::Base

  include Sort

  has_many :lessons
  has_many :words

  validates :title, presence: true, length: {maximum: 255}
  validates :detail, presence: true, length: {maximum: 255}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :load_category, only: [:edit, :update, :destroy]
  before_action :check_logged

  def index
    @category = Category.new
    @categories = Category.paginate(page: params[:page],
      per_page: Settings.categories_per_page).sort_desc
  end

  def new
    @categories = Category.new
  end

  def create
    @categories = Category.new category_params
    if @categories.save
      flash[:success] = t "page.categoriescontroller.createsuccess"
      redirect_to categories_path
    else
      flash[:danger] = t "page.categoriescontroller.createdanger"
      render :new
    end
  end

  def destroy
    if @category.words.any?
      flash[:danger] = t "category.deleteerror"
      redirect_to :back
    else
      if @category.destroy
        flash[:success] = t "category.deletesuccess"
      else
        flash[:danger] = t "category.deleteerror"
      end
      redirect_to :back
    end
  end

  def update
    @category.update_attributes category_params
    if @category.save
      flash[:success] = t "page.usercontroller.updatesuccess"
      redirect_to :back
    else
      flash[:danger] = t "page.usercontroller.updatefail"
      redirect_to :back
    end
  end

  private
  def load_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t "category.nil"
      render file: "public/404.html", status: :not_found, layout: true
    end
  end

  def category_params
    params.require(:category).permit :title, :detail
  end

end

app/views/categories/index.html.erb
<div class="table-responsive">

  <div class="row">
    <h2 class="col-md-2"><%= t "category.category" %></h2>
    <% if @current_user.is_admin? %>
      <%= link_to t("category.createcate"), new_category_path,
        class: "btn-info btn col-md-2 col-md-offset-7 createcate" %>
    <% end %>
  </div>
  <br>
  <table class="table table-striped edit">
    <thead>
    <tr>
      <th><%= t "category.index" %></th>
      <th><%= t "category.name" %></th>
      <th><%= t "category.detail" %></th>
      <th><%= t "category.action" %></th>
    </tr>
    </thead>
    <tbody>
    <% @categories.each_with_index do |category, index| %>
      <tr>
        <td><% if params[:page] ||= 1 %>
          <%= index_for params[:page], index, Settings.categories_per_page %>
          <% end %>
        </td>
        <td><%= category.title %></td>
        <td><%= category.detail %></td>
        <td>
          <% unless @current_user.is_admin? %>
            <button type="button" class="btn btn-info btn-md button-detail glyphicon
              glyphicon-info-sign" data-toggle="modal" data-target="#myModal_<%= category.id %>">
            </button>
          <% else %>
            <button type="button" class="btn btn-success btn-md button-detail glyphicon
              glyphicon-info-sign" data-toggle="modal" data-target="#myModal_<%= category.id %>">
            </button>
            <button type="button" class="btn btn-info btn-md button-detail glyphicon
              glyphicon-pencil" data-toggle="modal" data-target="#myModal_update_<%= category.id %>">
            </button>
            <button type="button" class="btn btn-danger btn-md button-detail glyphicon
              glyphicon-remove" data-toggle="modal" data-target="#myModal_delete_<%= category.id %>">
            </button>
          <% end %>
        </td>
      </tr>
      <div class="modal fade" id="myModal_<%= category.id %>" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"><strong><%= t "category.detail" %></strong></h4>
            </div>
            <div class="modal-body">
              <div class="row">
                <p class="text-left"><%= t "category.id" %>: <%= category.id %></p>
              </div>
              <div class="row"><p class="text-left">
                <p class="text-left"><%= t "category.name" %>: <%= category.title %></p>
              </div>
              <div class="row">
                <p class="text-left"><%= t "category.detail" %>: <%= category.detail %></p>
              </div>
              <br>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">
                <%= t "category.close" %></button>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id="myModal_update_<%= category.id %>" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"><strong><%= t "category.update" %></strong></h4>
            </div>
            <div class="modal-body">
              <%= form_for category, method: :put do |f| %>
                  <%= f.label :title %>
                  <%= f.text_field :title, class: "form-control", value: category.title %>
                  <%= f.label :detail %>
                  <%= f.text_field :detail, class: "form-control", value: category.detail %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">
                <%= t "category.close" %>
              </button>
              <%= f.submit t("category.update"), class: "btn btn-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id="myModal_delete_<%= category.id %>" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"><strong><%= t "category.delete" %></strong></h4>
            </div>
            <div class="modal-body">
              <p><%= t "category.areyou" %><strong><%= t "category.deletedowncase" %>
                </strong><%= t "category.record" %>
              </p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">
                <%= t "category.close" %></button>
              <%= link_to t("category.delete"), category_path(category.id),
                method: :delete , class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<div class="container-fluid background">
  <div class="row centered-form">
    <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title text-center"><%= t "category.category" %></h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-6 col-md-offset-3">
              <%= form_for @categories do |f| %>
                <%= f.label :title %>
                <%= f.text_field :title, class: "form-control" %>

                <%= f.label :detail %>
                <%= f.text_field :detail, class: "form-control" %>

                <%= f.submit t("page.view.category.create"), class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>