config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/home", to: "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/signup", to: "users#create"
  resources :users do
    member do
      get :following, :followers
    end
  end
  namespace :admin do
    resources :users, only: [:index]
    resources :words
  end
  resources :categories
  resources :words
  resources :relationships
  resources :lessons
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
          data-toggle="collapse" data-target="#navbar"
          aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">
            <%= t "page.header.toggleitem" %>
          </span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">
          <%= link_to image_tag("logo.png"), root_path %>
        </a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to t("page.header.homeitem"),
              root_path %>
          </li>
          <li>
            <%= link_to t("page.header.aboutitem"),
              about_path %>
          </li>
          <li>
            <%= link_to t("page.header.contactitem"),
              contact_path %>
          </li>
          <li>
            <%= link_to t("page.header.helpitem"),
              help_path %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <% unless @current_user.is_admin? %>
              <li>
                <%= link_to t("page.header.lessons"),
                  lessons_path %>
              </li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle"
                data-toggle="dropdown"
                role="button" aria-haspopup="true"
                aria-expanded="false">
                <%= t "page.header.accountitem" %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <% unless @current_user.is_admin? %>
                  <li>
                    <%= link_to t("page.header.profileitem"), user_path(@current_user) %>
                  </li>
                  <li>
                    <%= link_to t("page.header.signoutitem"),
                      logout_path, method: :delete %>
                  </li>
                  <li>
                    <%= link_to t("page.header.showlistuser"),
                      users_path %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to t("page.header.profileitem"), user_path(@current_user) %>
                  </li>
                  <li>
                    <%= link_to t("page.header.signoutitem"),
                      logout_path, method: :delete %>
                  </li>
                  <li>
                    <%= link_to t("page.header.showlistuser"),
                      admin_users_path %>
                  </li>
                <% end %>
              </ul>
            </li>
            <li>
              <%= link_to t("category.category"), categories_path %>
            </li>
            <li>
              <%= link_to t("category.word"), words_path %>
            </li>
          <% else %>
            <li>
              <%= link_to t("page.header.signupitem"), new_user_path %>
            </li>
            <li>
              <%= link_to t("page.header.signinitem"), login_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t "page.title" %></title>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": true %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container-fluid">
      <%= render "layouts/header" %>
      <div class="jumbotron content-main">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>">
            <%= message %>
          </div>
        <% end %>
      <%= yield %>
    </div>
  </body>
</html>